from . import res_company
from . import res_config_settings
from . import res_partner
from . import twikey_mandate_details
from . import account_move
from . import twikey_contract_template
from . import sale_order
from . import ir_config_parameter
from . import account_journal
from . import twikey_sync_contract_templates
from . import payment_acquirer
from . import payment_transaction
